# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/hacking-with-angular
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: iANGULAR

# favicon
favicon: /favicon.ico

# URL of the Home page image (piano player)
index_cover: http://angular.angular-china.org/830cf876-c3b2-4d1e-8657-adde1723f532.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # duoshuo
  duoshuo_shortname: hacking-with-angular
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/hacking-with-angular/hacking-with-angular.github.io
gitlab_url:
linkedin_url:
mailto: